WebApplication2/Models/OrderDetails.cs
using System.ComponentModel.DataAnnotations;
using WebApplication2.Data;

namespace WebApplication2.Models
{
    public class OrderDetails
    {
        public int Id { get; set; }
        [Required]
        public int OrderId { get; set; }
        [Required]
        public int ItemsId { get; set; }
        public int Quantity { get; set; }
        public Decimal UnitPrice { get; set; }
        public Order Order { get; set; }
        public Items Items { get; set; }


    }
}

WebApplication2/Controllers/UserOrderController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebApplication2.Data;
using WebApplication2.Models;
using WebApplication2.Repository;
using WebApplication2.ViewModels;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class UserOrderController : Controller
    {
        private readonly IUserOrderRepository _userOrderRepository;
        private readonly AppDbContext _appDbContext;
        private readonly IItemRepository _itemRepository;

        public UserOrderController(IUserOrderRepository userOrderRepository , AppDbContext appDbContext
           , IItemRepository itemRepository)
        {
            _userOrderRepository = userOrderRepository;
            _appDbContext = appDbContext;
            _itemRepository = itemRepository;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UsersOrders(string sortOrder, string statusFilter, string search, int page = 1, int pageSize = 6)
        {
            // Define the sorting parameters based on the sortOrder parameter
            ViewBag.IdSortParam = sortOrder == "id_asc" ? "id_desc" : "id_asc";
            ViewBag.DateSortParam = sortOrder == "date_asc" ? "date_desc" : "date_asc";

            // Retrieve the orders from the repository
            var orders = await _userOrderRepository.UsersOrders();

            // Filter the orders based on the selected OrderStatus filter
            if (!string.IsNullOrEmpty(statusFilter))
            {
                if (statusFilter == "All Statuses")
                {
                    ViewBag.SelectedStatusFilter = "All Statuses";
                }
                else
                {
                    orders = orders.Where(o => o.OrderStatus.StatusName.Contains(statusFilter)).ToList();
                    ViewBag.SelectedStatusFilter = statusFilter;
                }
            }

            // Apply the search term filter
            if (!string.IsNullOrEmpty(search))
            {
                search = search.ToLower(); // Convert search string to lowercase
                orders = orders.Where(o =>
                    o.User.FirstName.ToLower().Contains(search)
                    || o.User.LastName.ToLower().Contains(search)
                    || o.User.Email.ToLower().Contains(search)
                    || o.Id.ToString().ToLower().Contains(search)
                ).ToList();
            }

            // Apply the sorting based on the sortOrder parameter
            switch (sortOrder)
            {
                case "id_asc":
                    orders = orders.OrderBy(o => o.Id).ToList();
                    break;
                case "id_desc":
                    orders = orders.OrderByDescending(o => o.Id).ToList();
                    break;
                case "date_asc":
                    orders = orders.OrderBy(o => o.CreateDate).ToList();
                    break;
                case "date_desc":
                    orders = orders.OrderByDescending(o => o.CreateDate).ToList();
                    break;
                default:
                    orders = orders.OrderByDescending(o => o.CreateDate).ToList();
                    break;
            }

            // Get the distinct OrderStatus values from the orders
            var statusList = _appDbContext.OrderStatus.Select(o => o.StatusName).Distinct().ToList();

            // Insert "All Statuses" at the beginning of the statusList
            statusList.Insert(0, "All Statuses");

            ViewBag.StatusList = statusList;

            // Apply pagination to the orders
            int totalItems = orders.Count();
            orders = orders.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Pass the pagination information to the view
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItems = totalItems;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            // Pass the search term to the view
            ViewBag.SearchTerm = search;

            return View(orders);
        }
        
        public async Task<IActionResult> UserOrders(string sortOrder, string statusFilter, int page = 1, int pageSize = 6)
        {
            // Define the sorting parameters based on the sortOrder parameter
            ViewBag.IdSortParam = sortOrder == "id_asc" ? "id_desc" : "id_asc";
            ViewBag.DateSortParam = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            var orders = await _userOrderRepository.UserOrders();
            switch (sortOrder)
            {
                case "id_asc":
                    orders = orders.OrderBy(o => o.Id).ToList();
                    break;
                case "id_desc":
                    orders = orders.OrderByDescending(o => o.Id).ToList();
                    break;
                case "date_asc":
                    orders = orders.OrderBy(o => o.CreateDate).ToList();
                    break;
                case "date_desc":
                    orders = orders.OrderByDescending(o => o.CreateDate).ToList();
                    break;
                default:
                    orders = orders.OrderByDescending(o => o.CreateDate).ToList();
                    break;
            }
            // Apply pagination to the orders
            int totalItems = orders.Count();
            orders = orders.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Pass the pagination information to the view
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItems = totalItems;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            return View(orders);
        }
   
        public async Task<ViewResult> OrderDetails(int id ,  int page = 1, int pageSize = 3)
        {

            var order = await _userOrderRepository.GetByIdAsync(id);

            if (order == null) return View("Error");
            var orderVm = new OrderViewModel
            {
                OrderDetails = order.OrderDetails,
                UserId = order.UserId,
                Id = order.Id,
                OrderStatus = order.OrderStatus,
                OrderStatusId = order.OrderStatusId,
                User = order.User,
                CreateDate = order.CreateDate



            };
            int totalItems = orderVm.OrderDetails.Count();
            orderVm.OrderDetails = order.OrderDetails.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Pass the pagination information to the view
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItems = totalItems;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalItems / pageSize);
            ViewBag.OrderStatus = _appDbContext.OrderStatus.ToList();
            return View(orderVm);
        }
        public async Task<IActionResult> CancelOrder(int id)
        {

            var order = await _userOrderRepository.GetByIdAsync(id);

            if (order == null) return View("Error");
            order.OrderStatusId = 2;
            _appDbContext.Orders.Update(order);
            _appDbContext.SaveChanges();
            return RedirectToAction("UserOrders");
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteOrder(int id)
        {
            var order = await _userOrderRepository.GetByIdAsync(id);
            _userOrderRepository.Delete(order);
            return RedirectToAction("UsersOrders");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ViewResult> Edit(int id, int page = 1, int pageSize = 3)
        {

            var order = await _userOrderRepository.GetByIdAsync(id);

            if (order == null) return View("Error");
            var orderVm = new OrderViewModel
            {
                OrderDetails = order.OrderDetails,
                UserId = order.UserId,
                Id = order.Id,
                OrderStatus = order.OrderStatus,
                OrderStatusId = order.OrderStatusId,
                User = order.User,
                CreateDate = order.CreateDate



            };
            int totalItems = orderVm.OrderDetails.Count();
            orderVm.OrderDetails = order.OrderDetails.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Pass the pagination information to the view
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItems = totalItems;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalItems / pageSize);
            ViewBag.OrderStatus = _appDbContext.OrderStatus.ToList();
            return View(orderVm);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(OrderViewModel orderVm)
        {
           
            
           
            var order1 = new Order
            {
                UserId = orderVm.UserId,
                User = orderVm.User,
                Id = orderVm.Id,
                OrderDetails = orderVm.OrderDetails,
                OrderStatusId = orderVm.OrderStatusId,
                OrderStatus = orderVm.OrderStatus,
                CreateDate = orderVm.CreateDate,

            };
            if(orderVm.OrderStatusId == 3)
            {
                var Data = order1.OrderDetails.ToList().Where(x => x.OrderId == orderVm.Id);
                foreach (var data in Data)
                {
                    var item = _appDbContext.Items.AsNoTracking().FirstOrDefault(x => x.Id == data.ItemsId);
                    if (item != null)
                    {

WebApplication2/Views/UserOrder/Edit.cshtml
@model OrderViewModel
<style>

</style>
<form asp-action="Edit" asp-controller="UserOrder" >
    <div hidden="hidden">
        
        @for (int i = 0; i < Model.OrderDetails.Count(); i++)
        {

            @Html.EditorFor(model => model.OrderDetails[i])
            @Html.EditorFor(model=>model.CreateDate);

        }

        @Html.EditorFor(model => model.User)
       
    </div>
    

   

    
    <div class="container" style="margin-bottom:60px;">
        <div class="row card" style="margin-top:30px; margin-bottom:30px;">
            <h4>Customer Details</h4>
            <span class="text-secondary"><strong class="text-primary">Full Name:</strong> @Model.User.FirstName @Model.User.LastName</span>
            <span class="text-secondary"><strong class="text-primary">Email:</strong> @Model.User.Email</span>
            <span class="text-secondary"><strong class="text-primary">Phone Number:</strong> @Model.User.PhoneNumber</span>
            <span class="text-secondary"><strong class="text-primary">Address:</strong> @Model.User.Address</span>
        </div>
        
    <table class="table table-borderless table-hover">
        <tr class ="text-center">
            <th>Product</th>
            <th>Image</th>
            <th>Unit Price(INR)</th>
            <th>Total Price</th>
           
        </tr>
        @foreach (var item in Model.OrderDetails)
        {
            <tr class="text-center">
                <td>@item.Items.Name</td>
                <td>
                    <img class="card-img-top" src="@item.Items.CoverImageUrl" style="width:80px;height:80px; object-fit:contain">
                </td>
                
                <td>@item.Items.Price X @item.Quantity</td>
                <td>@(item.Items.Price * item.Quantity)</td>

            </tr>
        }
    </table>
        @if (ViewBag.TotalPages > 1)
        {
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <p>Page @ViewBag.CurrentPage of @ViewBag.TotalPages</p>
                </div>
                <div class="col-sm-12 col-md-6">

                    <ul class="pagination justify-content-end">
                        @if (ViewBag.CurrentPage == 1)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="@Url.Action("Edit", new {page = ViewBag.CurrentPage - 1 })">Previous</a></li>
                        }

                        @for (int i = 1; i <= ViewBag.TotalPages; i++)
                        {
                            if (i == ViewBag.CurrentPage)
                            {
                                <li class="page-item active"><a class="page-link" href="#">@i</a></li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" href="@Url.Action("Edit", new {page = i })">@i</a></li>
                            }
                        }

                        @if (ViewBag.CurrentPage == ViewBag.TotalPages)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="@Url.Action("Edit", new {page = ViewBag.CurrentPage + 1 })">Next</a></li>
                        }
                    </ul>

                </div>
            </div>
        }
    @if (Model.OrderStatusId != 3)
    {
        <strong class="text-primary">Order Status:</strong>
        @foreach (var orderStatus in ViewBag.OrderStatus)
        {
            <div>
                <input type="radio" id="orderStatus@(orderStatus.Id)" name="OrderStatusId" value="@orderStatus.Id" @(Model.OrderStatusId == orderStatus.Id ? "checked" : "")>
                <label for="orderStatus@(orderStatus.Id)">@orderStatus.StatusName</label>
            </div>

        }
            <div class="btn-group" style="margin-top:20px;">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Save Changes
                </button>
                <a class="btn btn-secondary" asp-controller="UserOrder" asp-action="DownloadOrderPdf" asp-route-id="@Model.Id">Download Voucher</a>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" style="margin-top:60px;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Save Changes</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you Sure ?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <input type="submit" value="Yes" class="btn btn-primary" />

                        </div>
                    </div>
                </div>
            </div>

    }
    else
    {
            <span class="text-secondary"><strong class="text-primary">Order Status:</strong> @Model.OrderStatus.StatusName</span>
        
    }

 
    </div>
    
</form>

WebApplication2/Views/UserOrder/UserOrders.cshtml
@model IEnumerable<Order>


<div class="container">

    @if (Model != null && Model.Count() > 0)
    {

        <div>
            <h4>Orders</h4>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            Order Id
                            <a asp-action="UserOrders" asp-controller="UserOrder"
                           asp-route-sortOrder="@Html.Raw(ViewBag.IdSortParam)">
                                @if (ViewBag.IdSortParam == "id_asc")
                                {
                                    <i class="bi bi-arrow-up"></i>
                                }
                                else
                                {
                                    <i class="bi bi-arrow-down"></i>
                                }
                            </a>
                        </th>
                        <th>
                            Order Date
                            <a asp-action="UserOrders" asp-controller="UserOrder"
                           asp-route-sortOrder="@Html.Raw(ViewBag.DateSortParam)">
                                @if (ViewBag.DateSortParam == "date_asc")
                                {
                                    <i class="bi bi-arrow-up"></i>
                                }
                                else
                                {
                                    <i class="bi bi-arrow-down"></i>
                                }
                            </a>
                        </th>
                        <th>Order Status</th>
                        <th>Ordered By</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var order in Model)
                {
                    <tr>
                        <td>@order.Id</td>
                        <td>@order.CreateDate.ToString("dd-MM-yyyy")</td>
                        <td>@order.OrderStatus.StatusName</td>
                        <td>@order.User.FirstName @order.User.LastName</td>
                        <td>

                            <a asp-action="OrderDetails" asp-controller="UserOrder" asp-route-id="@order.Id"><i class="bi bi-file-earmark-text"></i></a>
                            @if (order.OrderStatus.StatusName == "Pending")
                            {
                                    <span> /</span> <a asp-action="CancelOrder" asp-controller="UserOrder" asp-route-id="@order.Id" onclick="showCancelOrderModal(event)"><i class="bi bi-x-lg"></i></a>

                                    <div class="modal fade" id="cancelOrderModal" tabindex="-1" role="dialog" aria-labelledby="cancelOrderModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="cancelOrderModalLabel">Cancel Order</h5>
                                                  
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure you want to cancel this order?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                                    <a id="confirmCancelOrderButton" class="btn btn-primary" href="#">Yes</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            }
                            
                        </td>

                        
                    </tr>
                }
                </tbody>
            </table>

        </div>
        @if (ViewBag.TotalPages > 1)
        {
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <p>Page @ViewBag.CurrentPage of @ViewBag.TotalPages</p>
                </div>
                <div class="col-sm-12 col-md-6">

                    <ul class="pagination justify-content-end">
                        @if (ViewBag.CurrentPage == 1)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="@Url.Action("UserOrders", new { sortOrder = ViewBag.CurrentSort, statusFilter = ViewBag.SelectedStatusFilter, page = ViewBag.CurrentPage - 1 })">Previous</a></li>
                        }

                        @for (int i = 1; i <= ViewBag.TotalPages; i++)
                        {
                            if (i == ViewBag.CurrentPage)
                            {
                                <li class="page-item active"><a class="page-link" href="#">@i</a></li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" href="@Url.Action("UserOrders", new { sortOrder = ViewBag.CurrentSort, statusFilter = ViewBag.SelectedStatusFilter, page = i })">@i</a></li>
                            }
                        }

                        @if (ViewBag.CurrentPage == ViewBag.TotalPages)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="@Url.Action("UserOrders", new { sortOrder = ViewBag.CurrentSort, statusFilter = ViewBag.SelectedStatusFilter, page = ViewBag.CurrentPage + 1 })">Next</a></li>
                        }
                    </ul>

                </div>
            </div>
        }

    }
    else
    {
        <h4>No Orders</h4>
    }

</div>
@section Scripts{
    <script>
        function showCancelOrderModal(event) {
            event.preventDefault();
            $('#confirmCancelOrderButton').attr('href', event.currentTarget.href);
            $('#cancelOrderModal').modal('show');
        }
    </script>
}

WebApplication2/Views/UserOrder/UsersOrders.cshtml
@model IEnumerable<Order>

<div class="container mt-3">
    @if (Model != null && Model.Count() > 0)
    {
        <div>
            <h4>Orders</h4>
            <form method="get" asp-controller="UserOrder" asp-action="UsersOrders">
                <div class="input-group mb-3">
                    <input type="text" name="search" class="form-control" placeholder="Search by order ID, customer name or email" value="@ViewBag.SearchTerm" />
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </form>
            <table class="table table-striped">
              <thead>
                <tr>
                    <th>
                        Order Id
                        <a asp-action="UsersOrders" asp-controller="UserOrder"
                       asp-route-sortOrder="@Html.Raw(ViewBag.IdSortParam)">
                            @if (ViewBag.IdSortParam == "id_asc")
                            {
                                <i class="bi bi-arrow-up"></i>
                            }
                            else
                            {
                                <i class="bi bi-arrow-down"></i>
                            }
                        </a>
                    </th>
                    <th>
                        Order Date
                        <a asp-action="UsersOrders" asp-controller="UserOrder"
                       asp-route-sortOrder="@Html.Raw(ViewBag.DateSortParam)">
                            @if (ViewBag.DateSortParam == "date_asc")
                            {
                                <i class="bi bi-arrow-up"></i>
                            }
                            else
                            {
                                <i class="bi bi-arrow-down"></i>
                            }
                        </a>
                    </th>
                    <th style="width:300px; vertical-align:bottom; text-align:left;">
                        <div class="row align-items-end">
                            <div class="col-auto" style="vertical-align:bottom; text-align:left;">
                                <span>Order Status</span>
                            </div>
                            <div class="col-auto">
                                <form method="get" asp-controller="UserOrder" asp-action="UsersOrders">
                                    <select name="statusFilter" class="form-control" onchange="this.form.submit()">
                                        @if (ViewBag.SelectedStatusFilter == null)
                                        {
                                            <option value="">Sort by :</option>
                                        }
                                        <option value="@ViewBag.SelectedStatusFilter">@ViewBag.SelectedStatusFilter</option>
                                        @foreach (var status in ViewBag.StatusList)
                                        {
                                            @(status == ViewBag.SelectedStatusFilter ? "selected" : "")
                                            <option value="@status">@status</option>
                                        }
                                    </select>
                                </form>
                            </div>
                        </div>
                    </th>
                    <th>Ordered By</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var order in Model)
                {
                    <tr>
                        <td>@order.Id</td>
                        <td>@order.CreateDate.ToString("dd-MM-yyyy")</td>
                        <td>@order.OrderStatus.StatusName</td>
                        <td>@order.User.FirstName @order.User.LastName</td>
                        <td>
                            <a asp-action="Edit" asp-controller="UserOrder" asp-route-id="@order.Id"><i class="bi bi-pencil-square"></i></a>
                              <span> /</span> <a asp-action="DeleteOrder" asp-controller="UserOrder" asp-route-id="@order.Id" onclick="showCancelOrderModal(event)"><i class="bi bi-x-lg"></i></a>

                                <div class="modal fade" id="cancelOrderModal" tabindex="-1" role="dialog" aria-labelledby="cancelOrderModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="cancelOrderModalLabel">Delete Order</h5>

                                            </div>
                                            <div class="modal-body">
                                                Are you sure you want to delete this order?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                                <a id="confirmCancelOrderButton" class="btn btn-primary" href="#">Yes</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>

        @if (ViewBag.TotalPages > 1)
        {
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <p>Page @ViewBag.CurrentPage of @ViewBag.TotalPages</p>
                </div>
                <div class="col-sm-12 col-md-6">

                    <ul class="pagination justify-content-end">
                        @if (ViewBag.CurrentPage == 1)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="@Url.Action("UsersOrders", new { sortOrder = ViewBag.CurrentSort, statusFilter = ViewBag.SelectedStatusFilter, page = ViewBag.CurrentPage - 1 })">Previous</a></li>
                        }

                        @for (int i = 1; i <= ViewBag.TotalPages; i++)
                        {
                            if (i == ViewBag.CurrentPage)
                            {
                                <li class="page-item active"><a class="page-link" href="#">@i</a></li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" href="@Url.Action("UsersOrders", new { sortOrder = ViewBag.CurrentSort, statusFilter = ViewBag.SelectedStatusFilter, page = i })">@i</a></li>
                            }
                        }

                        @if (ViewBag.CurrentPage == ViewBag.TotalPages)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="@Url.Action("UsersOrders", new { sortOrder = ViewBag.CurrentSort, statusFilter = ViewBag.SelectedStatusFilter, page = ViewBag.CurrentPage + 1 })">Next</a></li>
                        }
                    </ul>

                </div>
            </div>
        }
    }
    else
    {
        <h4>No Orders</h4>
    }
</div>
@section Scripts{
    <script>
        function showCancelOrderModal(event) {
            event.preventDefault();
            $('#confirmCancelOrderButton').attr('href', event.currentTarget.href);
            $('#cancelOrderModal').modal('show');
        }
    </script>
}